apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vandychat-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vandychat-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

